#Configurações de Sincronização - Sistema Embarcação
#Wed Dec 17 12:38:57 AMT 2025
api.token=
server.url=http\://localhost\:8080
sync.auto=false
sync.interval=5
sync.ultima=2025-12-17T12\:38\:57.709519800
