import { useState, useEffect, useCallback } from 'react'
import { api } from '../api.js'
function formatMoney(v){return new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(v||0)}
function fmtDate(d){if(!d)return'\u2014';if(typeof d==='string'&&/^\d{2}\/\d{2}\/\d{4}$/.test(d))return d;const s=String(d).includes('T')?d.substring(0,10):d;try{const p=s.split('-');return p.length===3?`${p[2]}/${p[1]}/${p[0]}`:s}catch{return s}}
function todayISO(){return new Date().toISOString().split('T')[0]}
function addMonths(ds,m){const d=new Date(ds);d.setMonth(d.getMonth()+m);return d.toISOString().split('T')[0]}
export default function Boletos({viagemAtiva,onNavigate,onClose}){
const[boletos,setBoletos]=useState([]);const[categorias,setCategorias]=useState([]);const[loading,setLoading]=useState(false);const[toast,setToast]=useState(null);const[sel,setSel]=useState(null);const[filtroData,setFiltroData]=useState('');const[salvando,setSalvando]=useState(false);const[desc,setDesc]=useState('');const[catSel,setCatSel]=useState('');const[valor,setValor]=useState('');const[parcelas,setParcelas]=useState(1);const[dataVenc,setDataVenc]=useState(addMonths(todayISO(),1));const[obs,setObs]=useState('');const[modalBaixa,setModalBaixa]=useState(null);const[formaPag,setFormaPag]=useState('BOLETO')
function showToast(m,t='success'){setToast({msg:m,type:t});setTimeout(()=>setToast(null),3500)}
useEffect(()=>{api.get('/financeiro/categorias').then(d=>setCategorias(Array.isArray(d)?d:[])).catch(()=>{})},[])
const carregar=useCallback(()=>{setLoading(true);let url='/financeiro/boletos?';if(viagemAtiva)url+=`viagem_id=${viagemAtiva.id_viagem}&`;if(filtroData)url+=`data_vencimento=${filtroData}`;api.get(url).then(d=>setBoletos(Array.isArray(d)?d:[])).catch(()=>showToast('Erro','error')).finally(()=>setLoading(false))},[viagemAtiva,filtroData])
useEffect(()=>{carregar()},[carregar])
async function gerar(){if(!desc.trim()){showToast('Informe descricao','error');return}if(!valor||parseFloat(valor)<=0){showToast('Informe valor','error');return}if(!viagemAtiva){showToast('Selecione viagem','error');return}setSalvando(true);try{let idCat=null;if(catSel){const c=categorias.find(x=>x.nome===catSel);idCat=c?c.id:null}const vt=parseFloat(valor),qp=parseInt(parcelas)||1,vp=Math.round((vt/qp)*100)/100;for(let i=0;i<qp;i++){await api.post('/financeiro/saida',{id_viagem:viagemAtiva.id_viagem,descricao:qp>1?`${desc.trim().toUpperCase()} (${i+1}/${qp})`:desc.trim().toUpperCase(),valor_total:vp,valor_pago:0,data_vencimento:addMonths(dataVenc,i),id_categoria:idCat,forma_pagamento:'BOLETO',status:'PENDENTE',numero_parcela:i+1,total_parcelas:qp,observacoes:obs.trim()||null})}showToast(`${qp} boleto(s) gerado(s)!`);setDesc('');setValor('');setParcelas(1);setObs('');carregar()}catch(e){showToast(e.message||'Erro','error')}finally{setSalvando(false)}}
async function pagar(){if(!modalBaixa)return;setSalvando(true);try{await api.post(`/financeiro/saida/${modalBaixa.id}/baixa`,{forma_pagamento:formaPag});showToast('Pago!');setModalBaixa(null);carregar()}catch(e){showToast(e.message||'Erro','error')}finally{setSalvando(false)}}
async function excluir(){if(!sel){showToast('Selecione','error');return}if(!confirm(`Excluir "${sel.descricao}"?`))return;try{await api.delete(`/financeiro/saida/${sel.id}`,{motivo:'Exclusao boletos'});showToast('Excluido');setSel(null);carregar()}catch(e){showToast(e.message||'Erro','error')}}
const I={padding:'7px 10px',fontSize:'0.82rem',background:'var(--bg-soft)',border:'1px solid var(--border)',borderRadius:4,color:'var(--text)',width:'100%',boxSizing:'border-box'}
const L={fontSize:'0.72rem',fontWeight:700,color:'var(--text)',display:'block',marginBottom:3,marginTop:10}
return(<div>{toast&&<div className={`toast ${toast.type}`}>{toast.msg}</div>}<div style={{display:'flex',gap:12}}>
<div style={{width:300,flexShrink:0}}><div className="card" style={{padding:14}}>
<h3 style={{margin:'0 0 2px',fontSize:'0.95rem'}}>NOVO LANCAMENTO (A PRAZO)</h3><hr style={{border:'none',borderTop:'1px solid var(--border)',margin:'8px 0'}}/>
<label style={L}>Descricao / Fornecedor</label><input style={I} placeholder="Ex: Compra Pecas" value={desc} onChange={e=>setDesc(e.target.value)}/>
<label style={L}>Categoria</label><select style={I} value={catSel} onChange={e=>setCatSel(e.target.value)}><option value="">Digite para buscar...</option>{categorias.map(c=><option key={c.id} value={c.nome}>{c.nome}</option>)}</select>
<label style={L}>Valor Total (R$)</label><input style={{...I,background:'#FEF3C7',fontWeight:700}} type="number" step="0.01" placeholder="0,00" value={valor} onChange={e=>setValor(e.target.value)}/>
<label style={L}>Parcelamento (Quantidade)</label><input style={I} type="number" min="1" max="48" value={parcelas} onChange={e=>setParcelas(e.target.value)}/>
<label style={L}>Datas de Vencimento:</label><input style={I} type="date" value={dataVenc} onChange={e=>setDataVenc(e.target.value)}/>
<label style={L}>Observacoes</label><textarea style={{...I,minHeight:60,resize:'vertical'}} value={obs} onChange={e=>setObs(e.target.value)}/>
<button style={{width:'100%',padding:'10px',marginTop:14,background:'#047857',color:'#fff',border:'none',borderRadius:4,fontWeight:700,cursor:'pointer',fontSize:'0.9rem'}} onClick={gerar} disabled={salvando}>{salvando?'Gerando...':'GERAR BOLETOS'}</button>
</div></div>
<div style={{flex:1,minWidth:0}}><div className="card" style={{padding:0}}>
<div style={{display:'flex',justifyContent:'space-between',alignItems:'center',padding:'10px 14px',borderBottom:'1px solid var(--border)'}}>
<h3 style={{margin:0,fontSize:'0.95rem'}}>CONTROLE DE BOLETOS / PARCELAS</h3>
<div style={{display:'flex',gap:8,alignItems:'center'}}><span style={{fontSize:'0.78rem',fontWeight:700}}>Filtrar Vencimento:</span><input type="date" style={{...I,width:'auto',background:'#e0f5ef'}} value={filtroData} onChange={e=>setFiltroData(e.target.value)}/><button style={{padding:'5px 14px',background:'#047857',color:'#fff',border:'none',borderRadius:4,fontWeight:700,cursor:'pointer'}} onClick={carregar}>OK</button><button style={{padding:'5px 14px',background:'#DC2626',color:'#fff',border:'none',borderRadius:4,fontWeight:700,cursor:'pointer'}} onClick={()=>setFiltroData('')}>X</button></div>
</div>
<div style={{overflow:'auto',maxHeight:'calc(100vh - 250px)'}}>
<table style={{width:'100%',borderCollapse:'collapse',tableLayout:'fixed'}}><colgroup><col style={{width:'12%'}}/><col style={{width:'35%'}}/><col style={{width:'12%'}}/><col style={{width:'18%'}}/><col style={{width:'12%'}}/></colgroup>
<thead><tr style={{background:'#047857',color:'#fff',position:'sticky',top:0}}><th style={{padding:'6px 10px',fontSize:'0.72rem',textAlign:'left'}}>Vencimento</th><th style={{padding:'6px 10px',fontSize:'0.72rem',textAlign:'left'}}>Descricao</th><th style={{padding:'6px 10px',fontSize:'0.72rem',textAlign:'center'}}>Parcela</th><th style={{padding:'6px 10px',fontSize:'0.72rem',textAlign:'right'}}>Valor</th><th style={{padding:'6px 10px',fontSize:'0.72rem',textAlign:'center'}}>Status</th></tr></thead>
<tbody>{loading?<tr><td colSpan={5} style={{padding:30,textAlign:'center'}}>Carregando...</td></tr>:boletos.length===0?<tr><td colSpan={5} style={{padding:40,textAlign:'center',color:'var(--text-muted)'}}>Nao ha conteudo na tabela</td></tr>:boletos.map((b,i)=>{const isSel=sel?.id===b.id;const z=i%2===0?'rgba(4,120,87,0.06)':'transparent';const C={padding:'5px 10px',fontSize:'0.8rem',whiteSpace:'nowrap',overflow:'hidden',textOverflow:'ellipsis',maxWidth:0};return(<tr key={b.id} style={{background:isSel?'rgba(4,120,87,0.25)':z,cursor:'pointer'}} onClick={()=>setSel(b)} onMouseEnter={e=>{if(!isSel)e.currentTarget.style.background='rgba(4,120,87,0.15)'}} onMouseLeave={e=>{if(!isSel)e.currentTarget.style.background=z}}><td style={C}>{fmtDate(b.data_vencimento)}</td><td style={C} title={b.descricao}>{b.descricao||'\u2014'}</td><td style={{...C,textAlign:'center'}}>{b.numero_parcela&&b.total_parcelas?`${b.numero_parcela}/${b.total_parcelas}`:'\u2014'}</td><td style={{...C,textAlign:'right',fontFamily:'Space Mono,monospace',fontWeight:700}}>{formatMoney(b.valor_total)}</td><td style={{...C,textAlign:'center'}}><span className={`badge ${b.status==='PAGO'?'success':b.status==='VENCIDO'?'danger':'warning'}`} style={{fontSize:'0.68rem'}}>{b.status||'PENDENTE'}</span></td></tr>)})}</tbody></table></div>
<div style={{display:'flex',gap:10,justifyContent:'flex-end',padding:'10px 14px',borderTop:'1px solid var(--border)'}}>
<button style={{padding:'8px 20px',background:'#047857',color:'#fff',border:'none',borderRadius:4,fontWeight:700,cursor:'pointer',fontSize:'0.82rem',opacity:sel&&sel.status!=='PAGO'?1:0.5}} onClick={()=>{if(sel&&sel.status!=='PAGO'){setModalBaixa(sel);setFormaPag('BOLETO')}}} disabled={!sel||sel?.status==='PAGO'}>PAGAR SELECIONADO</button>
<button style={{padding:'8px 20px',background:'#DC2626',color:'#fff',border:'none',borderRadius:4,fontWeight:700,cursor:'pointer',fontSize:'0.82rem',opacity:sel?1:0.5}} onClick={excluir} disabled={!sel}>EXCLUIR</button>
<button style={{padding:'8px 20px',background:'#7BA393',color:'#fff',border:'none',borderRadius:4,fontWeight:700,cursor:'pointer',fontSize:'0.82rem'}} onClick={()=>onClose?onClose():onNavigate&&onNavigate('financeiro-saida')}>SAIR</button>
</div></div></div></div>
{modalBaixa&&(<div className="modal-overlay" onClick={()=>setModalBaixa(null)}><div className="modal" onClick={e=>e.stopPropagation()} style={{maxWidth:380}}><h3>Pagar Boleto</h3><p style={{marginBottom:8}}>{modalBaixa.descricao} — {formatMoney(modalBaixa.valor_total)}</p><label style={L}>Forma de Pagamento:</label><select style={I} value={formaPag} onChange={e=>setFormaPag(e.target.value)}><option>BOLETO</option><option>PIX</option><option>TRANSFERENCIA</option><option>DINHEIRO</option><option>CARTAO</option></select><div style={{display:'flex',gap:8,marginTop:14,justifyContent:'flex-end'}}><button className="btn-sm" onClick={()=>setModalBaixa(null)}>Cancelar</button><button style={{padding:'6px 16px',background:'#059669',color:'#fff',border:'none',borderRadius:4,fontWeight:700,cursor:'pointer'}} onClick={pagar} disabled={salvando}>{salvando?'...':'Confirmar'}</button></div></div></div>)}</div>)}
